#pragma once

#ifndef MAX_BONE_NUM_OF_VERTEX
#define MAX_BONE_NUM_OF_VERTEX	4
#endif // !MAX_BONE_NUM_OF_VERTEX

#ifndef MAX_VECTOR_RESERVE_SIZE
#define MAX_VECTOR_RESERVE_SIZE	 10000000
#endif // !MAX_VECTOR_RESERVE_SIZE

#ifndef MAX_GEOMETRY_DEFAULT_NUM
#define MAX_GEOMETRY_DEFAULT_NUM 1000
#endif // !MAX_GEOMETRY_DEFAULT_NUM

#ifndef MAX_BONE_NUM_OFMODEL
#define MAX_BONE_NUM_OFMODEL	96
#endif // !MAX_BONE_NUM_OFMODEL